# Generated by Django 4.2.5 on 2023-10-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users_birthdate_users_contact_users_emergencycontact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Birthdate',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
