# Generated by Django 4.2.5 on 2023-10-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_users_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Birthdate',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
    ]
