# Generated by Django 4.2.4 on 2023-08-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
    ]
