# Generated by Django 4.2.5 on 2023-10-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Birthdate',
            field=models.DateField(default='YYYY-MM-DD'),  # Replace with the correct format

        ),
        migrations.AddField(
            model_name='users',
            name='Contact',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='EmergencyContact',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='Macaddress',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='MedicalHistory',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='ValidationPeriod',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='add_card',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='card_select',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='users',
            name='card_uid',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='users',
            name='device_dep',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='device_uid',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='serialnumber',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='sex',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='users',
            name='user_date',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
