# Generated by Django 4.2.5 on 2023-10-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_users_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Birthdate',
        ),
    ]
